#!/usr/bin/env php
<?php
define('MODE_NAME', 'cli');  // 采用CLI运行模式运行
define('APP_DEBUG', true);
//// 定义应用目录
define( 'APP_PATH', dirname(__FILE__).'/Application/' );
define('PLUGIN_PATH', 'plugins/');
require dirname( __FILE__).'/ThinkPHP/ThinkPHP.php';

